language: java
jdk:
  - openjdk8
#before_install:
#  - chmod +x mvnw
#script:
#  - mvn -Ptest test -B
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
deploy:
- provider: packagecloud
  username: "${PACKAGECLOUD_USER}"
  repository: "${PACKAGECLOUD_REPO}"
  token: "${PACKAGECLOUD_TOKEN}"
  skip_cleanup: true
  on:
    branch: "develop"   
 